### Docker Compose example
services:
  mi_netkit:
    build:
      context: .
      dockerfile: Dockerfile
    image: sw-luis-palacios/base-netkit
    hostname: netkit
    container_name: mi_netkit
    ports:
      - "8822:22"    # Exposed ssh port
      - "8080:80"  # Exposed http port to nginx
      - "8443:443"  # Exposed https port to nginx (self certificate)
    environment:
      - HTTP_PORT=80         # Run nginx http listener on this port
      - HTTPS_PORT=443        # Run nginx http listener on this port
      - TITLE=Welcome to Netkit Container  # Titile to show on the default index.html
      - SUBTITLE=The web server is working
      - ROOT_PASSWORD=rootpass
      - NETKIT_PASSWORD=netkitpass
    volumes:
      - ./config:/config
